project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "MUSA 550 Final Project: Analyzing Philly's Quizzo Bars"
  site-url: "https://musa-550-fall-2023.github.io/quarto-website-template" 
  repo-url: https://github.com/MUSA-550-Fall-2023/quarto-website-template 
  repo-actions: [source]

  page-footer:
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-Nick Hand, 2023"

  sidebar:
    logo: "images/quizzo_.jpg"
    pinned: true
    align: center    
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Welcome
      - about.qmd
      - analysis/Philadelphia Quizzo.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




